name: Lint PR Checks

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: ESLint Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint
